spring:
 thymeleaf:
    cache: false
 imx:
   enabled: false
 datasource:
   driver-class-name:  com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/ecdb?serverTimsezone=Asia/Tokyo
   username: root
   password: mysql
   
mybatis:
  configuration:
   mapUnderscoreToCamelCase: true
  mapper-locations:
  - classpath*:/jp/co/internous/ecsite/model/mapper/**/*.xml
  
logging:
  level:
    org:
      springframework: WARN
    jp:
     co:
      internous:
         ecsite:
         model:
         mapper: DEBUG  
    
   
